# -*- coding: utf-8 -*-
"""Pull every quantity-bearing line out of the manuscript's Appendix C.

The manuscript is the chemistry AUTHORITY (CLAUDE.md), but nothing has ever checked
the authored game data against it: the suite's `content:` pins verify that a module
loads, has N tasks and is solvable, never that "5 drops" is authored as 5 squeezes.

This produces the RAW candidate list only. The machine-readable authority file,
Docs/manuscript-quantities.tsv, is curated by hand from this output, because the
manuscript's prose is not regular enough to trust a parser with -- and a wrong
"authority" file is worse than no authority file at all.

    python Tools/extract-manuscript-quantities.py

Reads  Docs/Documentations/manuscript.txt   (pdftotext -layout of manuscript.pdf)
Writes Docs/Documentations/manuscript-quantities-raw.txt
"""
import io
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "Docs", "Documentations", "manuscript.txt")
OUT = os.path.join(ROOT, "Docs", "Documentations", "manuscript-quantities-raw.txt")

# Appendix C only. Experiment 1 is a pen-and-paper stoichiometry exercise, not a
# bench lab, so the eight bench experiments are 2..9 (CLAUDE.md).
APPENDIX_C_FROM = 1860

QTY = re.compile(
    r"\b\d+(?:[.,]\d+)?\s*(?:-\s*\d+(?:[.,]\d+)?\s*)?"
    r"(?:ml\b|mL\b|g\b|gram|gm\b|drop|minute|min\b|hour|hr\b|"
    r"degree|celsius|percent|%|N\b|M\b|piece|spatula|dip)",
    re.I,
)

HEADING = re.compile(r"\s*EXPERIMENT NO\.\s*(\d+)")


def sections(lines):
    """Yield (experiment number, first line, last line) for Appendix C."""
    marks = []
    for i, line in enumerate(lines):
        m = HEADING.match(line)
        if m and i >= APPENDIX_C_FROM:
            marks.append((int(m.group(1)), i))
    # Several headings repeat per experiment (title page, data sheet, questions).
    # Keep the FIRST occurrence of each number, in order.
    first = {}
    for num, i in marks:
        first.setdefault(num, i)
    ordered = sorted(first.items(), key=lambda kv: kv[1])
    for idx, (num, start) in enumerate(ordered):
        end = ordered[idx + 1][1] if idx + 1 < len(ordered) else len(lines)
        yield num, start, end


def main():
    text = io.open(SRC, encoding="utf-8", errors="replace").read()
    lines = text.split("\n")

    out = [
        "Quantity-bearing lines from the manuscript's Appendix C.",
        "RAW CANDIDATES -- curate into Docs/manuscript-quantities.tsv by hand.",
        "Generated by Tools/extract-manuscript-quantities.py",
        "",
    ]
    total = 0
    for num, start, end in sections(lines):
        if num < 2:
            continue  # Experiment 1 is stoichiometry, a calculation exercise
        hits = []
        for i in range(start, end):
            stripped = lines[i].strip()
            if len(stripped) < 4:
                continue
            if QTY.search(stripped):
                hits.append((i + 1, stripped))
        total += len(hits)
        out.append("=" * 72)
        out.append("EXPERIMENT %d  (manuscript.txt lines %d-%d)  -- %d quantity lines"
                   % (num, start + 1, end, len(hits)))
        out.append("=" * 72)
        for lineno, hit in hits:
            out.append("  %6d  %s" % (lineno, hit))
        out.append("")

    io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(out))
    print("wrote %s (%d quantity lines across the 8 bench experiments)" % (OUT, total))


if __name__ == "__main__":
    main()
